/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.PathUpdater;
import java.awt.Dimension;

/**
 *
 * @author efren
 */
public class Toolbar extends javax.swing.JPanel {
    private final PathUpdater updater;
    
    /**
     * Creates new form Toolbar
     */
    public Toolbar(int width, PathUpdater updater) {
        initComponents();
        Dimension size= new Dimension(width, 20);
        setPreferredSize(size);
        setMaximumSize(size);
        setPreferredSize(size);
        
        this.updater=updater;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btstop = new javax.swing.JButton();
        btstart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btclear = new javax.swing.JButton();
        btstartPoint = new javax.swing.JButton();
        btendPoint = new javax.swing.JButton();
        btwalls = new javax.swing.JButton();
        btEraser = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btstop.setText("Stop");
        btstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btstopActionPerformed(evt);
            }
        });
        jPanel1.add(btstop);

        btstart.setText("Start");
        btstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btstartActionPerformed(evt);
            }
        });
        jPanel1.add(btstart);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Delay:");
        jPanel1.add(jLabel1);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel1.add(jSpinner1);

        add(jPanel1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMaximumSize(new java.awt.Dimension(5, 15));
        jSeparator1.setMinimumSize(new java.awt.Dimension(5, 15));
        jSeparator1.setName(""); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 15));
        add(jSeparator1);

        jPanel2.setAlignmentX(1.0F);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btclear.setText("Clear");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });
        jPanel2.add(btclear, new java.awt.GridBagConstraints());

        btstartPoint.setText("Set start point");
        btstartPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btstartPointActionPerformed(evt);
            }
        });
        jPanel2.add(btstartPoint, new java.awt.GridBagConstraints());

        btendPoint.setText("Set end point");
        btendPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btendPointActionPerformed(evt);
            }
        });
        jPanel2.add(btendPoint, new java.awt.GridBagConstraints());

        btwalls.setText("Draw walls");
        btwalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btwallsActionPerformed(evt);
            }
        });
        jPanel2.add(btwalls, new java.awt.GridBagConstraints());

        btEraser.setText("Erase");
        btEraser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEraserActionPerformed(evt);
            }
        });
        jPanel2.add(btEraser, new java.awt.GridBagConstraints());

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void btstartPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btstartPointActionPerformed
        updater.setBrush(100);
    }//GEN-LAST:event_btstartPointActionPerformed

    private void btwallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btwallsActionPerformed
        updater.setBrush(1);
    }//GEN-LAST:event_btwallsActionPerformed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        updater.clear();
    }//GEN-LAST:event_btclearActionPerformed

    private void btEraserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEraserActionPerformed
updater.setBrush(0);    }//GEN-LAST:event_btEraserActionPerformed

    private void btendPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btendPointActionPerformed
        updater.setBrush(200);
    }//GEN-LAST:event_btendPointActionPerformed

    private void btstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btstartActionPerformed
        new Thread(updater).start();
    }//GEN-LAST:event_btstartActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        updater.setDelay((Integer)jSpinner1.getValue());
    }//GEN-LAST:event_jSpinner1StateChanged

    private void btstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btstopActionPerformed
        updater.stop();
    }//GEN-LAST:event_btstopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEraser;
    private javax.swing.JButton btclear;
    private javax.swing.JButton btendPoint;
    private javax.swing.JButton btstart;
    private javax.swing.JButton btstartPoint;
    private javax.swing.JButton btstop;
    private javax.swing.JButton btwalls;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
